
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 30;
  public static final int DOUBLE = 19;
  public static final int LPAREN = 32;
  public static final int INT = 18;
  public static final int MINUS = 22;
  public static final int STATIC = 5;
  public static final int RPAREN = 33;
  public static final int SEMICOLON = 35;
  public static final int NOT = 15;
  public static final int AND = 26;
  public static final int LESSTHAN = 24;
  public static final int COMMA = 34;
  public static final int CLASS = 3;
  public static final int PLUS = 21;
  public static final int IF = 9;
  public static final int THIS = 13;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int RETURN = 8;
  public static final int RBRACKET = 31;
  public static final int TRUE = 16;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int BECOMES = 25;
  public static final int VOID = 6;
  public static final int TIMES = 23;
  public static final int LBRACE = 28;
  public static final int ELSE = 10;
  public static final int WHILE = 11;
  public static final int PUBLIC = 4;
  public static final int RBRACE = 29;
  public static final int EXTENDS = 7;
  public static final int DOUBLE_LITERAL = 38;
  public static final int FALSE = 17;
  public static final int LENGTH = 12;
  public static final int INTEGER_LITERAL = 37;
  public static final int IDENTIFIER = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "EXTENDS",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "LENGTH",
  "THIS",
  "NEW",
  "NOT",
  "TRUE",
  "FALSE",
  "INT",
  "DOUBLE",
  "BOOLEAN",
  "PLUS",
  "MINUS",
  "TIMES",
  "LESSTHAN",
  "BECOMES",
  "AND",
  "DOT",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "SEMICOLON",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "DOUBLE_LITERAL"
  };
}

